# Generated by Django 5.0 on 2025-11-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plannerprofile_delete_recruiterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLANNER', 'Planner'), ('ROAD_TRIPPER', 'Road Tripper')], db_index=True, default='ROAD_TRIPPER', max_length=20),
        ),
        migrations.DeleteModel(
            name='PlannerProfile',
        ),
    ]
