# Generated by Django 5.0 on 2025-09-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadTripper', '0003_remove_roadTripper_skills_roadTripper_skills'),
        ('roadTripper', '0004_roadTripper_hide_location'),
    ]

    operations = [
    ]
