# Generated by Django 5.0 on 2025-10-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('startDate', models.CharField(max_length=7, verbose_name='Start Date (mm/yyyy)')),
                ('endDate', models.CharField(blank=True, max_length=7, verbose_name='End Date (mm/yyyy)')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='roadTripper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to='roadTripper_images/', verbose_name='Profile Image')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('open_to_work', models.BooleanField(default=True)),
                ('desired_salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('desired_salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('startYear', models.IntegerField(blank=True, null=True, verbose_name='Start Year')),
                ('endYear', models.IntegerField(blank=True, null=True, verbose_name='End Year')),
                ('headline', models.TextField(blank=True)),
                ('hide_image', models.BooleanField(default=False)),
                ('hide_headline', models.BooleanField(default=False)),
                ('hide_profile', models.BooleanField(default=False)),
                ('hide_location', models.BooleanField(default=False)),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roadTripper', to='roadTripper.institution')),
                ('experience', models.ManyToManyField(blank=True, related_name='roadTripper', to='roadTripper.experience')),
                ('links', models.ManyToManyField(blank=True, related_name='roadTripper', to='roadTripper.link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadTripper_profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='roadTripper', to='roadTripper.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameHeadline', models.CharField(max_length=255, verbose_name='Name or Headline')),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_searches', to=settings.AUTH_USER_MODEL)),
                ('matches', models.ManyToManyField(blank=True, related_name='matched_searches', to='roadTripper.roadtripper')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='roadTripper_user_id_e76b39_idx')],
            },
        ),
    ]
