# Generated by Django 5.0 on 2025-10-26 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='roadTripper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Home Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to='roadTripper_images/', verbose_name='Profile Image')),
                ('travel_headline', models.CharField(blank=True, help_text='A short, catchy phrase about your travel style.', max_length=255, verbose_name='Travel Tagline')),
                ('travel_budget', models.CharField(choices=[('LOW', 'Budget-Friendly (Under $50/day)'), ('MID', 'Mid-Range (Approx. $50 - $150/day)'), ('HIGH', 'Luxury (Over $150/day)'), ('FLEX', 'Flexible / Varies')], default='MID', max_length=4, verbose_name='Travel Budget')),
                ('hide_image', models.BooleanField(default=False)),
                ('hide_travel_headline', models.BooleanField(default=False)),
                ('hide_profile', models.BooleanField(default=False)),
                ('hide_location', models.BooleanField(default=False)),
                ('destinations', models.ManyToManyField(blank=True, related_name='trippers_want_to_visit', to='roadTripper.destination')),
                ('interests', models.ManyToManyField(blank=True, related_name='trippers_with_interest', to='roadTripper.interest')),
                ('links', models.ManyToManyField(blank=True, related_name='roadTripper', to='roadTripper.link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadTripper_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='roadTripper_user_id_e76b39_idx')],
            },
        ),
    ]
