# Generated by Django 5.0 on 2025-10-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadTripper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtripper',
            name='hide_travel_budget',
            field=models.BooleanField(default=False),
        ),
    ]
