# Generated by Django 5.0 on 2025-11-02 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadTripper', '0002_roadtripper_hide_travel_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trip_photos/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadtripper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_posts', to='roadTripper.roadtripper')),
                ('tagged_friends', models.ManyToManyField(blank=True, related_name='tagged_in_trips', to='roadTripper.roadtripper')),
            ],
        ),
    ]
