# Generated by Django 5.0 on 2025-11-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadTripper', '0003_trippost'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippost',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trippost',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
