# Generated by Django 5.0 on 2025-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadTripper', '0004_trippost_lat_trippost_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippost',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
