# Generated by Django 5.0 on 2025-11-27 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadTripper', '0005_trippost_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trippost',
            name='like',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadTripper.trippost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadTripper.roadtripper')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
