# Generated by Django 5.0 on 2025-11-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='longitude',
        ),
    ]
