# Generated by Django 5.0 on 2025-12-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadTripper', '0007_comment'),
        ('trip', '0004_remove_stop_latitude_remove_stop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='numAvailSpots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='roadTrippers',
            field=models.ManyToManyField(related_name='roadTrippers', to='roadTripper.roadtripper'),
        ),
    ]
