# Generated by Django 5.0 on 2025-12-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadTripper', '0007_comment'),
        ('trip', '0005_trip_numavailspots_trip_roadtrippers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='roadTrippers',
            field=models.ManyToManyField(related_name='joined_trippers', to='roadTripper.roadtripper'),
        ),
    ]
