# Generated by Django 5.0 on 2025-12-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_alter_trip_roadtrippers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='numAvailSpots',
            new_name='numSignedUp',
        ),
    ]
