# Generated by Django 5.0 on 2025-12-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadTripper', '0007_comment'),
        ('trip', '0007_rename_numavailspots_trip_numsignedup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='roadTrippers',
            field=models.ManyToManyField(blank='True', related_name='joined_trippers', to='roadTripper.roadtripper'),
        ),
    ]
