# Generated by Django 5.0 on 2025-11-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Home Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to='planner_images/', verbose_name='Profile Image')),
                ('hide_image', models.BooleanField(default=False)),
                ('hide_travel_headline', models.BooleanField(default=False)),
                ('hide_travel_budget', models.BooleanField(default=False)),
                ('hide_profile', models.BooleanField(default=False)),
                ('hide_location', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
